# Generated by Django 4.2.4 on 2023-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_app', '0002_remove_snake_name_snake_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='submission_date',
            field=models.DateField(),
        ),
    ]
