# Generated by Django 4.2.4 on 2023-08-28 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snake_app', '0003_alter_snake_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='snake',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
