# Generated by Django 4.2.7 on 2023-11-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_app', '0005_remove_snake_upload_date_snake_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.TextField()),
                ('weights', models.FileField(upload_to='model_files/')),
            ],
        ),
    ]
