# Generated by Django 4.2.7 on 2023-11-22 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snake_app', '0007_alter_deeplearningmodel_architecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='caption',
        ),
        migrations.AddField(
            model_name='snake',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
